version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "human-friendly-Stack-V1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bjs7l5rbsh6"
s3_prefix = "human-friendly-Stack-V1"
region = "us-west-1"
profile = "savah"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
